a = int(input('first number: '))
b = int(input('second number: '))
Addition = (a+b)
Subtraction = (a-b)
Multiplication = (a*b)
Division = (a/b)

print('Addition', Addition)
print('Subtraction', Subtraction)
print('Multiplication', Multiplication)
print('Division', Division)